name: Prettier Format

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify markdown
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{md}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
